# FTSE Market Summary & Portfolio Analysis

KATE expects your code to define variables with specific names that correspond to certain things we are interested in.

KATE will run your notebook from top to bottom and check the latest value of those variables, so make sure you don't overwrite them.

* Remember to uncomment the line assigning the variable to your answer and don't change the variable or function names.
* Use copies of the original or previous DataFrames to make sure you do not overwrite them by mistake.

You will find instructions below about how to define each variable.

Once you're happy with your code, upload your notebook to KATE to check your feedback.

## About the Dataset

In the following section, you will be analysing **The Financial Times Stock Exchange 100 (FTSE 100) Index** data, pronounced, the 'Footsie hundred', is a share index of the 100 companies listed on the London Stock Exchange with the highest market capitalisation. 


The dataset includes information about:

- Company - Name of  the publicly traded company

- Ticker - A ticker or stock symbol is an abbreviation used to uniquely identify a stock on a particular stock market

- Sector - Industry in which the company operates in

- Mid-price (p) - Average between the 'buying' and the 'selling' price of a particular stock

- Change - Difference between the current price and the previous day's market price of a particular stock
    - A positive change is what allows investors to make a profit.

- Our view - View of the analyst or the brokerage firm collected this data

- Brokers - Total number of brokerage firms tracking and analysing the stock

- 'Strong Buy', 'Buy', 'Neutral', 'Sell', 'Strong Sell' - columns indicates the weighted verdict of all Brokers 

- Recommendation - Final verdict or recommendation for the stock
    - Overweight/Outperform means "buy", investors should assign a higher weighting to the stock in portfolios or funds 
    - Underweight/Underperform means "sell" or "don't buy" recommendation for a specific stock

## Importing Pandas Library

Make sure you run the following code cell import Pandas Library before you attempt any of the questions

In [1]:
import pandas as pd

## Importing the dataset

First use the `.read_csv()` function to import the file `FTSE100.csv` from the `data` folder, assigning it to `df` DataFrame. 

After using the `.head()` method to look at the first five rows of the `df` DataFrame. Also, consider using `.info()` method to further explore your data.

In [2]:
df = pd.read_csv('data/FTSE100.csv')
df.head()

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Strong Buy,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,"1,099.50",0.0171,Hold,5,NaN,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,"2,115.00",-0.42%,Hold,18,NaN,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,"1,744.00",0.0154,Hold,24,NaN,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,NaN,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,"2,207.00",0.0347,Buy,17,NaN,12,5,0,0,Buy

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Company         101 non-null    object
 1   Ticker          101 non-null    object
 2   Sector          101 non-null    object
 3   Mid-price (p)   101 non-null    object
 4   Change          101 non-null    object
 5   Our view        101 non-null    object
 6   Brokers         101 non-null    int64
 7   Strong Buy      0 non-null      float64
 8   Buy             101 non-null    int64
 9   Neutral         101 non-null    int64
 10  Sell            101 non-null    int64
 11  Strong Sell     101 non-null    int64
 12  Recommendation  101 non-null    object
dtypes: float64(1), int64(5), object(7)
memory usage: 10.4+ KB

## 1. Tidy Data


The dataset has a column with only `n/a` values, and also 101 rows (you may have been expecting 100!). This is because one of the companies (Royal Dutch Shell) has two entries. We can get rid of the first instance of these (RDSA).

Starting from a copy of `df`, create a new DataFrame called `clean_df` with the following changes:
- Drop the row with a `Ticker` value of `RDSA`
- Drop the `Strong Buy` column

In [4]:
#add your code below

#Make sure you call your new DataFrame clean_df
clean_df = df.copy()
clean_df = clean_df[clean_df['Ticker'] != 'RDSA']
clean_df = clean_df.drop(columns=['Strong Buy'])
clean_df

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation
0,3i,III,Financial Services,"1,099.50",0.0171,Hold,5,4,1,0,0,Buy
1,Admiral Group,ADM,Nonlife Insurance,"2,115.00",-0.42%,Hold,18,2,6,7,3,Underweight
2,Anglo American plc,AAL,Mining,"1,744.00",0.0154,Hold,24,15,6,2,0,Buy
3,Antofagasta,ANTO,Mining,848.2,0.0326,Hold,21,8,9,3,0,Overweight
4,Ashtead Group,AHT,Support Services,"2,207.00",0.0347,Buy,17,12,5,0,0,Buy
...,...,...,...,...,...,...,...,...,...,...,...,...
96,Unilever,ULVR,Personal Goods,"5,151.00",0.0029,Buy,16,6,6,2,1,Overweight
97,United Utilities,UU.,"Gas, Water & Multi-utilities",808,0.0025,Buy,12,4,4,1,2,Overweight
98,Vodafone Group,VOD,Mobile Telecommunications,155.88,0.0203,Buy,20,14,3,1,0,Buy
99,Whitbread,WTB,Retail hospitality,"4,357.00",0.0035,Hold,22,3,12,3,3,Neutral
100,WPP plc,WPP,Media,970.6,0.0208,Hold,21,10,9,1,1,Overweight

## 2. Change Column Data Type

Look at the values in the `Mid-price (p)` column. At first glance they may look like floats but in fact they have been interpreted as text. We need to change them to floats for them to be more useful.

Starting from a copy of `clean_df`, create a new DataFrame called  `price_df` with the following change:

- Convert the values in the `Mid-price (p)` column to floats (keeping the column in the same place)

*Hint: converting directly to a float may not work if there are commas in the strings; you may find the [str.replace](https://docs.python.org/3/library/stdtypes.html#str.replace) method useful for fixing this before conversion.*

In [5]:
#add your code below

#Make sure you call your new DataFrame price_df
price_df = clean_df.copy()
price_df['Mid-price (p)'] = price_df['Mid-price (p)'].str.replace(',', '').astype(float)

## 3. Format Change Values

Take a look at the values in the `Change` column. You'll see that they are in an inconsistent format, and stored as strings. The positive values need to be multiplied by 100. The negative values need to have the `%` sign removed.

**Part 1:** Create a function called `format_change` which takes a string such as those in the `Change` column and does the following:
1. If the last character is a % sign, remove it 
2. Convert the string to a float
3. If that float is posiive, multiply it by 100
4. Return the resulting float

*Hint: to convert string to a float you may find [float()](https://www.w3schools.com/python/ref_func_float.asp) function useful*

In [6]:
#add your code below


def format_change(change_str):
    # Check if the last character is a % sign
    
    if change_str.endswith('%'):
        
        # Remove the % sign
        change_str = change_str[:-1]
        
    # Convert the string to a float
    change_value = float(change_str)
    
    # If the value is positive, multiply it by 100
    if change_value > 0:
        return change_value * 100
        
    # Return the resulting float
    return change_value

Uncomment and run the following code cell to test that your function works as expected:

In [7]:
format_change('0.45%')

45.0

**Part 2:** Starting from a copy of `price_df`, create a new DataFrame called  `change_df` with a new column called `Change (%)`:

- This should contain the result returned from the function created above when given the original `Change` column value as the argument

In [8]:
#add your code below

#Make sure you call your new DataFrame change_df

change_df = price_df.copy()
change_df['Change (%)'] = change_df['Change'].apply(format_change)

# Output the new DataFrame
change_df

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%)
0,3i,III,Financial Services,1099.50,0.0171,Hold,5,4,1,0,0,Buy,1.71
1,Admiral Group,ADM,Nonlife Insurance,2115.00,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42
2,Anglo American plc,AAL,Mining,1744.00,0.0154,Hold,24,15,6,2,0,Buy,1.54
3,Antofagasta,ANTO,Mining,848.20,0.0326,Hold,21,8,9,3,0,Overweight,3.26
4,Ashtead Group,AHT,Support Services,2207.00,0.0347,Buy,17,12,5,0,0,Buy,3.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Unilever,ULVR,Personal Goods,5151.00,0.0029,Buy,16,6,6,2,1,Overweight,0.29
97,United Utilities,UU.,"Gas, Water & Multi-utilities",808.00,0.0025,Buy,12,4,4,1,2,Overweight,0.25
98,Vodafone Group,VOD,Mobile Telecommunications,155.88,0.0203,Buy,20,14,3,1,0,Buy,2.03
99,Whitbread,WTB,Retail hospitality,4357.00,0.0035,Hold,22,3,12,3,3,Neutral,0.35
100,WPP plc,WPP,Media,970.60,0.0208,Hold,21,10,9,1,1,Overweight,2.08

## 4. Holding Summary

You are given the details of a share holding in a tuple, containing the company ticker code, number of shares, and price paid. Make sure you run the following code cell before attempting the question.

In [9]:
holding = ('BP.', 500, 1535.21)

print(holding[0])
print(holding[1])
print(holding[2])

BP.
500
1535.21

Starting from the `holding` above and `change_df`, build a new dictionary containing the following keys and the appropriate values in the given data formats.

```
{    
    holding_cost: float,    
    # The cost (in £, not pence) of the holding (number of shares * price paid)
    holding_value: float,    
    # The value (in £, not pence) of the holding (number of shares * current mid-price) 
    change_in_value: float,    
    # The percentage change from the original cost of the holding to the current value  
    (e.g. if the holding_value is 1.2 * the holding_cost, the change_in_value should equal 20.0)
    
}
```

Call this dictionary `holding_dict`


*Hint: If you want to get the first item in a series of values (such as a column of a filtered DataFrame), you can use* `.values[0]` *on the column*

In [10]:
#add your code below

#Make sure you call your new dictionary holding_dict
#holding_dict = ...


bp_mid = change_df[change_df['Ticker'] == 'BP.']['Mid-price (p)'].values[0]

holding_cost = (holding[1]*holding[2])/100

holding_value = (holding[1]*bp_mid)/100

change_in_value = ((holding_value-holding_cost)/holding_cost)*100

holding_dict = {'holding_cost':holding_cost, 'holding_value':holding_value, 'change_in_value':change_in_value}

holding_dict

{'holding_cost': 7676.05,
 'holding_value': 8665.0,
 'change_in_value': 12.883579445157336}

## 5. Market Comparison

Provided with the DataFrame you processed above, `change_df`, we would like to compare the % change in the mid-price for each company to the average % change for all companies in the market, along with a summary of the broker recommendations.

Create a DataFrame called `comparison_df` with the following columns added to a copy of `change_df`: 

- **'Beat Market'** - This should be a Boolean column with `True` for stocks where `Change (%)` exceeds that of the average market change
- **'Buy Ratio'** - This should equal the `Buy` column divided by the `Brokers` column

*Hint: Calculate the average market change % first then compare each value in the `Change (%)` column to that when creating the new column*

In [11]:
#add your code below

#Make sure you call your new DataFrame comparison_df
comparison_df = change_df.copy()

ave_change = comparison_df['Change (%)'].mean()
comparison_df['Beat Market'] = comparison_df['Change (%)'] > ave_change
comparison_df['Buy Ratio'] = comparison_df['Buy']/comparison_df['Brokers']


comparison_df

,Company,Ticker,Sector,Mid-price (p),Change,Our view,Brokers,Buy,Neutral,Sell,Strong Sell,Recommendation,Change (%),Beat Market,Buy Ratio
0,3i,III,Financial Services,1099.50,0.0171,Hold,5,4,1,0,0,Buy,1.71,True,0.800000
1,Admiral Group,ADM,Nonlife Insurance,2115.00,-0.42%,Hold,18,2,6,7,3,Underweight,-0.42,False,0.111111
2,Anglo American plc,AAL,Mining,1744.00,0.0154,Hold,24,15,6,2,0,Buy,1.54,True,0.625000
3,Antofagasta,ANTO,Mining,848.20,0.0326,Hold,21,8,9,3,0,Overweight,3.26,True,0.380952
4,Ashtead Group,AHT,Support Services,2207.00,0.0347,Buy,17,12,5,0,0,Buy,3.47,True,0.705882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Unilever,ULVR,Personal Goods,5151.00,0.0029,Buy,16,6,6,2,1,Overweight,0.29,False,0.375000
97,United Utilities,UU.,"Gas, Water & Multi-utilities",808.00,0.0025,Buy,12,4,4,1,2,Overweight,0.25,False,0.333333
98,Vodafone Group,VOD,Mobile Telecommunications,155.88,0.0203,Buy,20,14,3,1,0,Buy,2.03,True,0.700000
99,Whitbread,WTB,Retail hospitality,4357.00,0.0035,Hold,22,3,12,3,3,Neutral,0.35,False,0.136364
100,WPP plc,WPP,Media,970.60,0.0208,Hold,21,10,9,1,1,Overweight,2.08,True,0.476190

## 6. Investigate

We want to identify any companies which match a given set of rules, so that we can look into them further.   

We want to identify companies in `watchlist` that meet at least one of the following requirements:

i) Any company in `watchlist` whose prices is equal to or lower than the given target price.

ii) Any company in `watchlist` where `Buy Ratio` is 0.5 or greater.

Using the `watchlist` below and `comparison_df` you defined, create a list of companies meeting the requirements, call this list `companies_list`. The list should only have the company names, not the price.

Note: **A company meeting both requirements should only appear once in the list**.

*Hint: create an empty list to add company names to, using a loop to work through the watchlist. If you want to get the first item in a series of values (such as a column of a filtered DataFrame), you can use* `.values[0]` *on the column.*

In [12]:
watchlist = [('TUI', 820.0), ('Whitbread', 4300.0), ('AstraZeneca', 7500.0), 
             ('Standard Chartered', 920.0), ('Barclays', 135.5)]
watchlist

[('TUI', 820.0),
 ('Whitbread', 4300.0),
 ('AstraZeneca', 7500.0),
 ('Standard Chartered', 920.0),
 ('Barclays', 135.5)]

In [13]:
#add your code below

#Make sure you call your new empty list companies_list
companies_list = []

for item in watchlist:
    mid_p = comparison_df[comparison_df['Company'] == item[0]]['Mid-price (p)'].values[0]
    buy_r = comparison_df[comparison_df['Company'] == item[0]]['Buy Ratio'].values[0]
    
    if mid_p <= item [1] or buy_r >= 0.5:
        companies_list.append(item[0])
        
companies_list

['TUI', 'AstraZeneca', 'Standard Chartered']