**Following guidelines set expectations for participant behaviour during workshop activities. They also ensure that the class environment is welcoming, inclusive, and respectful.**
- Where a discussion is taking place, allow everyone a chance to speak
- Listen respectfully, without interrupting and with an open mind to understanding others’ views
- Be professional and productive, and always share your ideas, your opinion matters, we all can learn something from each other
- Personal information that comes up in the conversation should be kept confidential
- Avoid inflammatory language
- Avoid assumptions about any member of the class or generalisations about social groups

**You have now joined a group of fellow analysts in a workshop:**
#### Outcomes:

- To complete a group activity to identify how Pandas could be useful for your job role
- To be able to answer the questions to test your knowledge of Pandas


#### Note:
- We understand learners will progress at their own speed
- Tutors will be on hand to answer questions

## Group activity

- Identify how **Pandas** could be useful for your job role? And share your thoughts

In [1]:
#add your notes below

## ☑️ Part 1: Importing, examining, and updating values in a dataset

- Complete the following questions
- Make sure you run the following code cells before you attempt any of the questions
- First, import Pandas Library for analysing and manipulating data

In [2]:
import pandas as pd

Now use the `.read_csv()` function to import the file `libraries.csv` from the `data` folder, assigning the result to `df`:

In [3]:
df = pd.read_csv('data/libraries.csv')

### Exploratory data analysis

**Q1)** Check that the file has been imported as expected using the `.head()` method to look at the first `3` rows of `df` dataframe:

In [4]:
#add your code below
df.head(3)

,Library service,Library name,In use 2010,In use 2016,Type of library,Type of closed library,Closed,New building,Replace existing,Notes,Weekly hours open,Weekly hours staffed
0,Barking and Dagenham,Barking,Yes,Yes,LAL,NaN,NaN,NaN,NaN,NaN,72.0,72.0
1,Barking and Dagenham,Castle Green,Yes,No,NaN,XL,Mar-13,NaN,NaN,Closed as a public library 31.3.2013. Secondar...,NaN,NaN
2,Barking and Dagenham,Dagenham,No,Yes,LAL,NaN,NaN,Oct-10,Yes,Replaced Fanshawe and Rectory libraries,56.0,56.0

**Q2)** Use the `.info()` method on `df` to look at structure of the dataframe:

In [5]:
#add your code below
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3277 entries, 0 to 3276
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Library service         3276 non-null   object
 1   Library name            3276 non-null   object
 2   In use 2010             3275 non-null   object
 3   In use 2016             3267 non-null   object
 4   Type of library         3033 non-null   object
 5   Type of closed library  248 non-null    object
 6   Closed                  239 non-null    object
 7   New building            246 non-null    object
 8   Replace existing        234 non-null    object
 9   Notes                   1061 non-null   object
 10  Weekly hours open       2798 non-null   float64
 11  Weekly hours staffed    2797 non-null   float64
dtypes: float64(2), object(10)
memory usage: 307.3+ KB

**Q3)** Use the `.describe()` method on `df` to look at summary statistics for the numerical data columns:

In [6]:
#add your code below
df.describe()

       Weekly hours open  Weekly hours staffed
count        2798.000000           2797.000000
mean           35.734407             35.737529
std            30.952803             30.957897
min           -57.000000            -57.000000
25%            21.000000             21.000000
50%            33.500000             33.500000
75%            45.000000             45.000000
max           674.340000            674.340000

Notice that the value for `min` in both columns is negative, which suggests an error in the data.

**Q4)** You're told that there is an error in the row with index `2233`, use `.loc[]` method to have a look at this row and further investigate the error:

In [7]:
#add your code below

df.loc[2233]

Library service                                                 Oxfordshire
Library name                                                 Oxford Central
In use 2010                                                             yes
In use 2016                                                              no
Type of library                                                         LAL
Type of closed library                                                  XLT
Closed                                                                 2016
New building                                                            NaN
Replace existing                                                        NaN
Notes                     Refurbished 2012.  Currently, temporarily clos...
Weekly hours open                                                     -57.0
Weekly hours staffed                                                  -57.0
Name: 2233, dtype: object

**Q5)** Using `.loc[]` method update the values for both `Weekly hours open` and `Weekly hours staffed` with a value of `57`.

In [8]:
#add your code below

df.loc[2233, ['Weekly hours open', 'Weekly hours staffed']] = 57
df.loc[2233]

Library service                                                 Oxfordshire
Library name                                                 Oxford Central
In use 2010                                                             yes
In use 2016                                                              no
Type of library                                                         LAL
Type of closed library                                                  XLT
Closed                                                                 2016
New building                                                            NaN
Replace existing                                                        NaN
Notes                     Refurbished 2012.  Currently, temporarily clos...
Weekly hours open                                                      57.0
Weekly hours staffed                                                   57.0
Name: 2233, dtype: object

Once updated, re-run your code for the previous questions `Q3` and `Q4` to check that both values on the row at index `2233` have been updated. 

The `min` value for both `Weekly hours open` and `Weekly hours staffed` should now be `0`:

## ☑️ Part 2: Conditional filtering and modifying DataFrames
- Complete the following questions
- Make sure you re-run all the above code cells before you attempt any of the following questions

**Q6)** Use the `.set_index()` method with `inplace=True` parameter, to set the values from the `Library name` column as the index of `df`

In [9]:
#add your code below
df.set_index('Library name', inplace=True)
df.head()

,Library service,In use 2010,In use 2016,Type of library,Type of closed library,Closed,New building,Replace existing,Notes,Weekly hours open,Weekly hours staffed
Library name,,,,,,,,,,,
Barking,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,NaN,72.0,72.0
Castle Green,Barking and Dagenham,Yes,No,NaN,XL,Mar-13,NaN,NaN,Closed as a public library 31.3.2013. Secondar...,NaN,NaN
Dagenham,Barking and Dagenham,No,Yes,LAL,NaN,NaN,Oct-10,Yes,Replaced Fanshawe and Rectory libraries,56.0,56.0
Fanshawe,Barking and Dagenham,Yes,No,NaN,XLR,Sep-10,NaN,NaN,Closed September 2010 replaced by Dagenham Lib...,NaN,NaN
Marks Gate,Barking and Dagenham,Yes,Yes,CRL,NaN,NaN,NaN,NaN,Volunteer led with local authority staff suppo...,9.0,9.0

**Q7)** Use the `.drop()` method with `axis=1` and `inplace=True` parameters, to remove the `Notes` column from `df`

In [10]:
#add your code below
df.drop(['Notes'], axis=1, inplace=True)
df.head()

,Library service,In use 2010,In use 2016,Type of library,Type of closed library,Closed,New building,Replace existing,Weekly hours open,Weekly hours staffed
Library name,,,,,,,,,,
Barking,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,72.0,72.0
Castle Green,Barking and Dagenham,Yes,No,NaN,XL,Mar-13,NaN,NaN,NaN,NaN
Dagenham,Barking and Dagenham,No,Yes,LAL,NaN,NaN,Oct-10,Yes,56.0,56.0
Fanshawe,Barking and Dagenham,Yes,No,NaN,XLR,Sep-10,NaN,NaN,NaN,NaN
Marks Gate,Barking and Dagenham,Yes,Yes,CRL,NaN,NaN,NaN,NaN,9.0,9.0

### Some additional data preparation is needed before we continue with the rest of the questions. You will learn these techniques in more detail in the next module.

Let's use the `.value_counts()` method on `df['In use 2010']` and `df['In use 2016']`to see what different values there are in those columns:

In [11]:
df['In use 2010'].value_counts()

In use 2010
yes    2807
Yes     256
no      163
No       49
Name: count, dtype: int64

In [12]:
df['In use 2016'].value_counts()

In use 2016
yes    2550
no      384
Yes     213
No      120
Name: count, dtype: int64

In the cell below, we have defined a function called **`is_open()`**, which takes a single value and returns a boolean value as follows:
- `True` if the value equals `'yes'` or `'Yes'`
- `False` for any other value (`'no'` or `'No'`)

Run the cell to make the function available. You do not need to modify it for this exercise!

In [13]:
def is_open(entry):
    
    if entry in ['yes', 'Yes']:
        return True
    else:
        return False

The following cell contains some examples that allow us to test the logic in our function:

In [14]:
is_open('No'), is_open('yes')

(False, True)

Let's use the `.apply()` method with the `is_open()` function and each of the columns `In use 2010` and `In use 2016`, to create new columns called `open_2010` and `open_2016` respectively, each containing Boolean values returned by the function:

In [15]:
df['open_2010'] = df['In use 2010'].apply(is_open)
df['open_2016'] = df['In use 2016'].apply(is_open)

df.head()

,Library service,In use 2010,In use 2016,Type of library,Type of closed library,Closed,New building,Replace existing,Weekly hours open,Weekly hours staffed,open_2010,open_2016
Library name,,,,,,,,,,,,
Barking,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,72.0,72.0,True,True
Castle Green,Barking and Dagenham,Yes,No,NaN,XL,Mar-13,NaN,NaN,NaN,NaN,True,False
Dagenham,Barking and Dagenham,No,Yes,LAL,NaN,NaN,Oct-10,Yes,56.0,56.0,False,True
Fanshawe,Barking and Dagenham,Yes,No,NaN,XLR,Sep-10,NaN,NaN,NaN,NaN,True,False
Marks Gate,Barking and Dagenham,Yes,Yes,CRL,NaN,NaN,NaN,NaN,9.0,9.0,True,True

**Q8)** Create a new dataframe called `df_open`, which should only contain Boolean `True` entries for both `open_2010` and `open_2016`

- Hint: You can start by creating a Boolean mask

In [16]:
#add your code below

mask1 = (df['open_2010'] == True) & (df['open_2016'] == True)

df_open = df[mask1]

df_open.head()

,Library service,In use 2010,In use 2016,Type of library,Type of closed library,Closed,New building,Replace existing,Weekly hours open,Weekly hours staffed,open_2010,open_2016
Library name,,,,,,,,,,,,
Barking,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,72.0,72.0,True,True
Marks Gate,Barking and Dagenham,Yes,Yes,CRL,NaN,NaN,NaN,NaN,9.0,9.0,True,True
Robert Jeyes Community Library,Barking and Dagenham,Yes,Yes,CRL,NaN,NaN,NaN,NaN,14.5,14.5,True,True
Thames View,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,30.0,30.0,True,True
Valence,Barking and Dagenham,Yes,Yes,LAL,NaN,NaN,NaN,NaN,36.0,36.0,True,True

**Q9)** Calculate the `.mean()` of the values in the `Weekly hours open` column in `df_open` dataframe:

In [17]:
#add your code below
df_open['Weekly hours open'].mean()

36.99346725592607

**Q10)** Calculate the percentage of entries in `df_open` where `['Weekly hours open'] == 0`:

- Hint: You can make use of `len()` function

In [18]:
#add your code below
(len(df_open[(df_open['Weekly hours open'] == 0)])/len(df_open))*100

2.123625331816458

# Additional notes

## Exploring the impact of `NaN` values

Converting the zero values to `NaN` values will result those values being excluded from subsequent calculations, for example, `.mean()`.

These `NaN` values ('Not a Number') represent 'missing data' (of all types, not just numeric) in pandas.

Let's import numpy library with the **alias** of `np`, this is mainly done to access `np.nan` marker, this marker is used to represent `NaN` values.

In [19]:
import numpy as np

In [20]:
np.nan

nan

**Now let's use `.replace()` to modify the `Weekly hours open` column:**

In [21]:
df_open['Weekly hours open'] = df_open['Weekly hours open'].replace(0, np.nan)

/tmp/ipykernel_32/2557172181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_open['Weekly hours open'] = df_open['Weekly hours open'].replace(0, np.nan)

**Let's use the same code as before to calculate the `.mean()` of `Weekly hours open` to see if the value is now different.**

In [22]:
df_open['Weekly hours open'].mean()

37.8449404027949