**Following guidelines set expectations for participant behaviour during workshop activities. They also ensure that the class environment is welcoming, inclusive, and respectful.**
- Where a discussion is taking place, allow everyone a chance to speak
- Listen respectfully, without interrupting and with an open mind to understanding others’ views
- Be professional and productive, and always share your ideas, your opinion matters, we all can learn something from each other
- Personal information that comes up in the conversation should be kept confidential
- Avoid inflammatory language
- Avoid assumptions about any member of the class or generalisations about social groups

**You have now joined a group of fellow analysts in a workshop:**
#### Outcomes:

- To be able to answer the questions to test your knowledge of Text mining techniques


#### Note:
- We understand learners will progress at their own speed
- Tutors will be on hand to answer questions

# 🚀 Text mining Practical

In this workbook, we will be using data gathered from a community event in Austin, Texas hosted by the police to discuss racial profiling.

All of the required packages and modules can be imported by running the following cell:

In [1]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords, wordnet 
from nltk.stem import WordNetLemmatizer
from textblob import TextBlob

In [2]:
df = pd.read_csv('data/policing.csv')
df.head()

,Response,Question,Group,Topic,Theme
0,I have been an Austin resident for 1.5 years w...,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
1,Long term Austin resident and UT student,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
2,works for councilmember Delia Garza,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
3,to learn and gain new perspective,What was your motivation for attending this ev...,3,Motivations and Feelings,People expressed interest in this community di...
4,"Social work experience, and to take info/exper...",What was your motivation for attending this ev...,5,Motivations and Feelings,People expressed interest in this community di...

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Response  329 non-null    object
 1   Question  316 non-null    object
 2   Group     329 non-null    int64
 3   Topic     308 non-null    object
 4   Theme     329 non-null    object
dtypes: int64(1), object(4)
memory usage: 13.0+ KB

## Part 1: Word Frequency

Run the following code cell to assign the text to the variable `motivation_question`

In [4]:
motivation_question = 'What was your motivation for attending this event?'

**Q1)**  Create a new DataFrame named `motivation` that filters `df` to include only the rows where the value in the `'Question'` column is equal to the value stored in the variable `motivation_question`.

💡 *Hint:* Use a condition like `df['Question'] == motivation_question` in your filter.

In [5]:
# Add your code below
# motivation = ...

motivation = df[df['Question'] == motivation_question]
motivation.head()

,Response,Question,Group,Topic,Theme
0,I have been an Austin resident for 1.5 years w...,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
1,Long term Austin resident and UT student,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
2,works for councilmember Delia Garza,What was your motivation for attending this ev...,1,Motivations and Feelings,People expressed interest in this community di...
3,to learn and gain new perspective,What was your motivation for attending this ev...,3,Motivations and Feelings,People expressed interest in this community di...
4,"Social work experience, and to take info/exper...",What was your motivation for attending this ev...,5,Motivations and Feelings,People expressed interest in this community di...

**Q2)**  Create a **list** called `motivation_words` that contains **all the individual words** found in the `Response` column of the `motivation` DataFrame.

Steps to follow:  
- Start by creating an empty list named `motivation_words`  
- Use a `for` loop to go through each entry in `motivation['Response']`  
- Within the loop, use `word_tokenize()` to split each response into individual words  
- Use `.extend()` to add the tokens to the list `motivation_words`  
- Note: Do not remove duplicates, stop words, or modify word casing at this stage.


See below code syntax for some guidance:
```python
motivation_words = []

for text in <column_name>:
    words = word_tokenize(text)
    motivation_words.extend(words)

motivation_words
```

In [6]:
# Add your code below
# motivation_words = ...

motivation_words = []

for text in motivation['Response']:
    words = word_tokenize(text)
    motivation_words.extend(words)

motivation_words

['I',
 'have',
 'been',
 'an',
 'Austin',
 'resident',
 'for',
 '1.5',
 'years',
 'with',
 'family',
 'here',
 ';',
 'family',
 'is',
 'racially',
 'mixed',
 ',',
 'my',
 'son',
 'is',
 'stopped',
 'a',
 'lot',
 'in',
 'Philadelphia',
 'Long',
 'term',
 'Austin',
 'resident',
 'and',
 'UT',
 'student',
 'works',
 'for',
 'councilmember',
 'Delia',
 'Garza',
 'to',
 'learn',
 'and',
 'gain',
 'new',
 'perspective',
 'Social',
 'work',
 'experience',
 ',',
 'and',
 'to',
 'take',
 'info/experience',
 'back',
 'to',
 'their',
 'commision',
 'To',
 'better',
 'understand',
 'Help',
 'contribute',
 'to',
 'discussion',
 'and',
 'work',
 'on',
 'solutions',
 'Self',
 'education',
 'Share',
 'outcomes',
 'Anti-racism',
 'consulting',
 ',',
 'power',
 'dynamics',
 'in',
 'social',
 'systems',
 'Public',
 'policy',
 'researcher',
 'and',
 'grad',
 'student',
 'at',
 'UT',
 ',',
 'studies',
 'community',
 'and',
 'police',
 'relations',
 'and',
 'does',
 'stuff',
 'with',
 'Equity',
 'Office',
 'Race',
 'equity',
 'journey',
 'Curious',
 'to',
 'hear',
 'community',
 'input',
 'APD',
 'commander',
 'over',
 '10',
 'years',
 ';',
 'opportunity',
 'to',
 'hear',
 'from',
 'community',
 'and',
 'achieve',
 'city',
 'goals',
 ';',
 'lived',
 'all',
 'over',
 'Austin',
 'since',
 'the',
 '1980s',
 'and',
 'saw',
 'disparities',
 'Community',
 'engagement',
 'Community',
 'engagement',
 'Affordable',
 'housing',
 'interests',
 'for',
 'low-income',
 'people',
 'of',
 'color',
 'Equity',
 'office',
 'Identify',
 'issues',
 'and',
 'share',
 'experience',
 'with',
 'Undoing',
 'White',
 'Supremacy',
 'Austin',
 ',',
 'solutions',
 'for',
 'accountability',
 'and',
 'transparency',
 'Works',
 'with',
 'APD',
 'and',
 'has',
 '2',
 'perspectives',
 ':',
 'long',
 'time',
 'resident',
 'and',
 'police',
 'officer',
 'perspective',
 '.',
 'Vested',
 'interest',
 'in',
 'improving',
 'accountability',
 'Important',
 'issues',
 'Community',
 'Liaison',
 ',',
 'police',
 'officer',
 'experience',
 'Learn',
 'new',
 'perspective',
 'Local',
 'issues',
 'work',
 'in',
 'community',
 'and',
 'want',
 'to',
 'make',
 'an',
 'impact',
 'in',
 'Williamson',
 'County',
 'listen',
 ',',
 'understand',
 ',',
 'be',
 'part',
 'of',
 'solutions',
 'Impacted',
 ',',
 'here',
 'to',
 'listen',
 'and',
 'learn',
 'Be',
 'part',
 'of',
 'conversation',
 'Over',
 '10',
 'years',
 'working',
 'to',
 'hold',
 'APD',
 'accountable',
 'Austin',
 'Interfaith',
 'member',
 'and',
 'organizer',
 'Be',
 'part',
 'of',
 'conversation',
 'Important',
 'conversation',
 'Excited',
 'about',
 'seeing',
 'tangible',
 'recommendations',
 'East',
 'Austin',
 'resident',
 'for',
 '30+',
 'years',
 'and',
 'witness',
 'to',
 'aggressive',
 'policing',
 'Personal',
 'experience',
 'of',
 'neighbors',
 'am',
 'a',
 'Black',
 'person',
 'living',
 'in',
 'Austin',
 'experiencing',
 'disparities',
 'discussed',
 'in',
 'the',
 'report',
 'Personal',
 'experience',
 'with',
 'racial',
 'profiling',
 'Neighborhood',
 'has',
 'been',
 'historically',
 'policed',
 'Long-time',
 'resident',
 'of',
 'East',
 'and',
 'South',
 'Austin',
 ',',
 'attorney',
 ',',
 'concerned',
 'about',
 'the',
 'data',
 'and',
 'thinks',
 'it',
 'refutes',
 'racial',
 'profiling',
 'Disrespectful',
 'feeling',
 'from',
 'police',
 'Different',
 'Experience',
 'for',
 'white',
 'people',
 'in',
 'neighborhood',
 'Works',
 'in',
 'immigration',
 'and',
 'this',
 'hits',
 'close',
 'to',
 'home',
 'Concerns',
 'for',
 'impact',
 'on',
 'undocumented',
 'people',
 'Under',
 'policing',
 'for',
 'White',
 'people',
 'No',
 'confusion',
 'about',
 'accountability',
 'Owning',
 'up',
 'to',
 'the',
 'disparity',
 'Concerning',
 'that',
 'the',
 'police',
 'chief',
 'thinks',
 'it',
 'is',
 'better',
 'What',
 'are',
 'the',
 'police',
 'going',
 'to',
 'do',
 'about',
 'recommendations',
 '?',
 'Police',
 'have',
 'not',
 'prepared',
 'to',
 'respond',
 'to',
 'the',
 'report',
 'Not',
 'feeling',
 'any',
 'urgency',
 'from',
 'the',
 'police',
 'Bring',
 'lived',
 'experiences',
 'to',
 'the',
 'conversation',
 'for',
 'solutions',
 'and',
 'moving',
 'forward',
 'Addressing',
 'anti-blackness',
 'Changing',
 'the',
 'frame/structure',
 '.',
 'Having',
 'a',
 'parallel',
 'approach',
 'Social',
 'determinants',
 'of',
 'health',
 'Working',
 'on',
 'public',
 'health',
 'issues',
 'with',
 'students',
 'Bring',
 'healthcare',
 'perspective']

Assign to the variable `top_5` a `list` of the five most common words in `motivation_words`:
- use `nltk.freqdist` and the `.most_common()` method
- extract the words from the resulting tuples

In [7]:
freqdist = nltk.FreqDist(motivation_words).most_common(5)
freqdist

[('and', 21), ('to', 16), (',', 11), ('the', 10), ('for', 9)]

In [8]:
top_5 = [entry[0] for entry in freqdist]
top_5

['and', 'to', ',', 'the', 'for']

**Q3)**  Create a **cleaned list of words** called `motivation_clean`, derived from `motivation_words`, with the following conditions applied:

- All words should be **converted to lowercase**  
- All **English stopwords** should be **removed**  
- Only words made up of **alphabetical characters** should be kept (e.g. no punctuation, numbers, etc.)
- Use [.isalpha()](https://www.w3schools.com/python/ref_string_isalpha.asp) method to check if a word contains only letters.





See below code syntax for some guidance:
```python
motivation_clean = [word.lower() for word in motivation_words 
      if word.lower() not in stopwords.words('english') 
      and word.isalpha()]

motivation_clean
```

In [9]:
# Add your code below
# motivation_clean = ...

motivation_clean = [word.lower() for word in motivation_words 
      if word.lower() not in stopwords.words('english') 
      and word.isalpha()]

motivation_clean

['austin',
 'resident',
 'years',
 'family',
 'family',
 'racially',
 'mixed',
 'son',
 'stopped',
 'lot',
 'philadelphia',
 'long',
 'term',
 'austin',
 'resident',
 'ut',
 'student',
 'works',
 'councilmember',
 'delia',
 'garza',
 'learn',
 'gain',
 'new',
 'perspective',
 'social',
 'work',
 'experience',
 'take',
 'back',
 'commision',
 'better',
 'understand',
 'help',
 'contribute',
 'discussion',
 'work',
 'solutions',
 'self',
 'education',
 'share',
 'outcomes',
 'consulting',
 'power',
 'dynamics',
 'social',
 'systems',
 'public',
 'policy',
 'researcher',
 'grad',
 'student',
 'ut',
 'studies',
 'community',
 'police',
 'relations',
 'stuff',
 'equity',
 'office',
 'race',
 'equity',
 'journey',
 'curious',
 'hear',
 'community',
 'input',
 'apd',
 'commander',
 'years',
 'opportunity',
 'hear',
 'community',
 'achieve',
 'city',
 'goals',
 'lived',
 'austin',
 'since',
 'saw',
 'disparities',
 'community',
 'engagement',
 'community',
 'engagement',
 'affordable',
 'housing',
 'interests',
 'people',
 'color',
 'equity',
 'office',
 'identify',
 'issues',
 'share',
 'experience',
 'undoing',
 'white',
 'supremacy',
 'austin',
 'solutions',
 'accountability',
 'transparency',
 'works',
 'apd',
 'perspectives',
 'long',
 'time',
 'resident',
 'police',
 'officer',
 'perspective',
 'vested',
 'interest',
 'improving',
 'accountability',
 'important',
 'issues',
 'community',
 'liaison',
 'police',
 'officer',
 'experience',
 'learn',
 'new',
 'perspective',
 'local',
 'issues',
 'work',
 'community',
 'want',
 'make',
 'impact',
 'williamson',
 'county',
 'listen',
 'understand',
 'part',
 'solutions',
 'impacted',
 'listen',
 'learn',
 'part',
 'conversation',
 'years',
 'working',
 'hold',
 'apd',
 'accountable',
 'austin',
 'interfaith',
 'member',
 'organizer',
 'part',
 'conversation',
 'important',
 'conversation',
 'excited',
 'seeing',
 'tangible',
 'recommendations',
 'east',
 'austin',
 'resident',
 'years',
 'witness',
 'aggressive',
 'policing',
 'personal',
 'experience',
 'neighbors',
 'black',
 'person',
 'living',
 'austin',
 'experiencing',
 'disparities',
 'discussed',
 'report',
 'personal',
 'experience',
 'racial',
 'profiling',
 'neighborhood',
 'historically',
 'policed',
 'resident',
 'east',
 'south',
 'austin',
 'attorney',
 'concerned',
 'data',
 'thinks',
 'refutes',
 'racial',
 'profiling',
 'disrespectful',
 'feeling',
 'police',
 'different',
 'experience',
 'white',
 'people',
 'neighborhood',
 'works',
 'immigration',
 'hits',
 'close',
 'home',
 'concerns',
 'impact',
 'undocumented',
 'people',
 'policing',
 'white',
 'people',
 'confusion',
 'accountability',
 'owning',
 'disparity',
 'concerning',
 'police',
 'chief',
 'thinks',
 'better',
 'police',
 'going',
 'recommendations',
 'police',
 'prepared',
 'respond',
 'report',
 'feeling',
 'urgency',
 'police',
 'bring',
 'lived',
 'experiences',
 'conversation',
 'solutions',
 'moving',
 'forward',
 'addressing',
 'changing',
 'parallel',
 'approach',
 'social',
 'determinants',
 'health',
 'working',
 'public',
 'health',
 'issues',
 'students',
 'bring',
 'healthcare',
 'perspective']

Let’s explore the creation of the DataFrame `top_50_df`, with two columns:

- `Word`, containing the 50 most common words in `motivation_clean`
- `Count`, containing the number of occurrences of the given word in `motivation_clean`

*These values can be found in the list of tuples created when using `nltk.FreqDist()` and the `.most_common()` method.*

In [10]:
freqdist_clean = nltk.FreqDist(motivation_clean).most_common(50)
top_50_df = pd.DataFrame(freqdist_clean, columns=['Word', 'Count'])
top_50_df

               Word  Count
0            austin      8
1            police      8
2         community      7
3        experience      6
4          resident      5
5             years      4
6       perspective      4
7         solutions      4
8            people      4
9            issues      4
10     conversation      4
11            works      3
12            learn      3
13           social      3
14             work      3
15           equity      3
16              apd      3
17            white      3
18   accountability      3
19             part      3
20           family      2
21             long      2
22               ut      2
23          student      2
24              new      2
25           better      2
26       understand      2
27            share      2
28           public      2
29           office      2
30             hear      2
31            lived      2
32      disparities      2
33       engagement      2
34          officer      2
35        important      2
36           impact      2
37           listen      2
38          working      2
39  recommendations      2
40             east      2
41         policing      2
42         personal      2
43           report      2
44           racial      2
45        profiling      2
46     neighborhood      2
47           thinks      2
48          feeling      2
49            bring      2

Consider the resulting DataFrame, and whether `lemmatisation` or `stemming` might be appropriate (or some other form of grouping the words).

There are no definite answers - we might think that 'officer' and 'officers' could be grouped, but perhaps these could also be grouped with 'police' and even 'apd' (Austin Police Department).

We might consider using synonyms or suchlike but it may also be more appropriate to group manually, or not at all.

## Part 2: Sentiment Analysis

Adding a column to `df` called `Response_Sentiment`, which contains a value given by the `.sentiment.polarity` attribute of a `TextBlob` object created from the text of each entry in the `Response` column:

    The polarity score is a float within the range [-1.0, 1.0]
    -1.0 defines a negative sentiment and 1.0 defines a positive sentiment

In [11]:
df['Response_Sentiment'] = df['Response'].apply(lambda x: TextBlob(x).sentiment.polarity)
df[['Response', 'Response_Sentiment']]

                                              Response  Response_Sentiment
0    I have been an Austin resident for 1.5 years w...            0.000000
1             Long term Austin resident and UT student           -0.050000
2                  works for councilmember Delia Garza            0.000000
3                    to learn and gain new perspective            0.136364
4    Social work experience, and to take info/exper...            0.016667
..                                                 ...                 ...
324  A: Yes- types of calls, traffic sttops being m...            0.000000
325  There is retaliation from APD. Is it work some...            0.000000
326                 Name, motivation, police brutality            0.000000
327                    Q: When did APD get the report?            0.000000
328  What is policy v what is practice? Important t...            0.400000

[329 rows x 2 columns]

We can then use the `.describe()` method on the Series of values:

In [12]:
df['Response_Sentiment'].describe()

count    329.000000
mean       0.048662
std        0.209676
min       -0.700000
25%        0.000000
50%        0.000000
75%        0.100000
max        0.750000
Name: Response_Sentiment, dtype: float64

Run the following code cell to assign the text to the variable `feedback_question`

In [13]:
feedback_question = "How do you feel about what you have learned about the Racial Profiling Report so far? \
What came up for you reading the data or listening to the panel?"

**Q4)**  Create a new DataFrame called `feedback` by filtering `df` to only include rows where the `Question` column matches the `feedback_question` variable provided earlier.

💡 *Hint:* Use a condition like `df['Question'] == feedback_question` in your filter.

In [14]:
# Add your code below
# feedback = ...

feedback = df[df['Question'] == feedback_question]
feedback.head()

,Response,Question,Group,Topic,Theme,Response_Sentiment
36,Data source: glad to have detailed sources cited,How do you feel about what you have learned ab...,5,Data,People highlighted the strengths of the racial...,0.450000
37,Translate reports in Spanish,How do you feel about what you have learned ab...,3,Data,People highlighted the strengths of the racial...,0.000000
38,Surprised by the depth and data,How do you feel about what you have learned ab...,5,Data,People highlighted the strengths of the racial...,0.100000
39,This report is a step above what's been done i...,How do you feel about what you have learned ab...,1,Data,People highlighted the strengths of the racial...,0.135625
40,Surprised by SD23 zero-disparity goal,How do you feel about what you have learned ab...,5,Data,People highlighted the strengths of the racial...,0.100000

We can see that there are three different values in the `Topic` column, with a fairly even distribution between them:

In [15]:
feedback['Topic'].value_counts()

Topic
Racism/Systems    28
Accountability    21
Data              17
Name: count, dtype: int64

Creation of a DataFrame called `topic_sentiment`, using `.groupby()` on `feedback`, which shows the `mean`, `min`, and `max` `Response_Sentiment` values for each `Topic`: 

*You may find the pandas `.agg(['mean', 'min', 'max'])` method useful.*

In [16]:
topic_sentiment = feedback.groupby('Topic')['Response_Sentiment'].agg(['mean', 'min', 'max'])
topic_sentiment

                    mean       min   max
Topic
Accountability  0.004603 -0.700000  0.50
Data            0.082406 -0.222222  0.45
Racism/Systems -0.057440 -0.700000  0.40

We would like to see if there was much variation in sentiment between the five different groups which participated.

Creation of a DataFrame called `group_sentiment` (adapting the same code as above) to find the same `Response_Sentiment` metrics, this time for all `Responses` in `df` and grouped by `Group`:

In [17]:
group_sentiment = df.groupby('Group')['Response_Sentiment'].agg(['mean', 'min', 'max'])
group_sentiment

           mean       min   max
Group
1      0.068331 -0.230769  0.50
2     -0.019617 -0.700000  0.50
3      0.041355 -0.250000  0.50
4      0.030904 -0.700000  0.70
5      0.097806 -0.400000  0.75