**Following guidelines set expectations for participant behaviour during workshop activities. They also ensure that the class environment is welcoming, inclusive, and respectful.**
- Where a discussion is taking place, allow everyone a chance to speak
- Listen respectfully, without interrupting and with an open mind to understanding others’ views
- Be professional and productive, and always share your ideas, your opinion matters, we all can learn something from each other
- Personal information that comes up in the conversation should be kept confidential
- Avoid inflammatory language
- Avoid assumptions about any member of the class or generalisations about social groups

**You have now joined a group of fellow analysts in a workshop:**
#### Outcomes:

- To be able to answer the questions to test your knowledge of SQL queries


#### Note:
- We understand learners will progress at their own speed
- Tutors will be on hand to answer questions

## Group activity

- Identify how **SQL** could be useful for your job role? (5 mins).

In [1]:
#add your notes below

# ☑️ Data Exploration Using SQL

- Complete the following questions
- Make sure you run the following code cells before you attempt any of the questions
- We will work with `flights.db` database through this workbook

First, import pandas and sqlite3 libraries and create the connection to the `flights.db` database, located in the `data` folder:

In [2]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data/flights.db')

A database might have multiple tables. It's a good idea to do an initial exploration of the database by first querying the `sqlite_master` table to see what tables are in the database.

Run the following code cell to show all the tables in the `flights.db` database:

In [3]:
query = """
SELECT name 
FROM sqlite_master 
WHERE type = 'table';
"""
df = pd.read_sql_query(query, conn)
df

       name
0  airports
1  airlines
2    routes

Run the following code cell to show the schema for each table in `flights.db` database:

In [4]:
for table in ['airports','airlines','routes']:
    
    query = f"""
    SELECT sql 
    FROM sqlite_master 
    WHERE name = '{table}';
    """
    
    df = pd.read_sql_query(query, conn)
    print(''.join(df.values[0, 0]))

CREATE TABLE airports (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [city] TEXT,
  [country] TEXT,
  [code] TEXT,
  [icao] TEXT,
  [latitude] TEXT,
  [longitude] TEXT,
  [altitude] TEXT,
  [offset] TEXT,
  [dst] TEXT,
  [timezone] TEXT
)
CREATE TABLE airlines (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [alias] TEXT,
  [iata] TEXT,
  [icao] TEXT,
  [callsign] TEXT,
  [country] TEXT,
  [active] TEXT
)
CREATE TABLE routes (
[index] INTEGER,
  [airline] TEXT,
  [airline_id] TEXT,
  [source] TEXT,
  [source_id] TEXT,
  [dest] TEXT,
  [dest_id] TEXT,
  [codeshare] TEXT,
  [stops] TEXT,
  [equipment] TEXT
)

# ☑️ SQL Statements

**Q1)** Refer to the `airlines` table and show all columns of the table:
- Then, show first 5 rows using pandas `head()` method
- Use `%%time` at the beginning of a cell, to measure the query execution time

Please note you have been provided with the code for this question to carry out the necessary analysis work. Simply run the code cell to produce the desired results.

In [5]:
%%time

query = """
SELECT * 
FROM airlines;
"""

df = pd.read_sql_query(query, conn)
df.head()

CPU times: user 16.2 ms, sys: 4.04 ms, total: 20.3 ms
Wall time: 18.7 ms

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

**Q2)** Refer to the `airlines` table. Now do the same as above, but this time returning 5 rows using SQL. Measure the time again using `%%time`. This time query execution time should be faster.

Please note you have been provided with the code for this question to carry out the necessary analysis work. Simply run the code cell to produce the desired results.

In [6]:
%%time

query = """
SELECT * 
FROM airlines
LIMIT 5;
"""

df = pd.read_sql_query(query, conn)
df

CPU times: user 2.22 ms, sys: 1.09 ms, total: 3.3 ms
Wall time: 2.35 ms

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

It is advisable to take a moment to reflect upon the outcomes of questions 1 and 2, ensuring a thorough understanding of the results. Additionally, make sure to jot down any intriguing observations that arise from the analysis.

In [7]:
#add your notes below

**Q3)** Refer to the `country` column in `airlines` table. Find 7 airlines from United Kingdom.

- To extract all records that matches `United Kingdom` the filter condition `country = 'United Kingdom'` can be used

See below code syntax for some guidance:
```SQL
SELECT *
FROM airlines
WHERE <filter_condition>
LIMIT 7;
```

In [8]:
#add your code below
#query = ...


df = pd.read_sql_query(query, conn)
df

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

# ☑️ Advanced Filtering with WHERE
## Predicates

**Q4)** Refer to the `airlines` table. Find airlines having `icao` equal to ACC or TWF. 

See below code syntax for some guidance:
```SQL
SELECT *
FROM airlines
WHERE icao IN <list_of_values>;
```
The `list_of_values` to be compared to the column using the IN operator should be enclosed in parentheses. Eg: ('ACC','TWF').

In [9]:
#add your code below
#query = ...


df = pd.read_sql_query(query, conn)
df.head(5)

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

**Q5)** Refer to `name` column in the `airlines` table. Find 5 airlines whose names contains the word `Flight`.

See below code syntax for some guidance:
```SQL
SELECT *
FROM airlines
WHERE name LIKE <pattern>
LIMIT 5;
```
For example, the pattern %Airline% - matches any string that contains the word "Airline" (uppercase or lowercase).

In [10]:
#add your code below
#query = ...


df = pd.read_sql_query(query, conn)
df

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

**Q6)** Refer to `name`, `active`, and `callsign` columns in the `airlines` table. Find 5 active airlines having a non-empty callsign value. 

- Look for all records that match the conditions where: `active`=`'Y'` and `callsign` column `IS NOT NULL`

See below code syntax for some guidance:
```SQL
SELECT name, active, callsign
FROM airlines
WHERE <condition1> AND <condition2>
LIMIT 5;
```

In [11]:
#add your code below
#query = ...

df = pd.read_sql_query(query, conn)
df

,index,id,name,alias,iata,icao,callsign,country,active
0,0,1,Private flight,\N,-,None,None,None,Y
1,1,2,135 Airways,\N,None,GNL,GENERAL,United States,N
2,2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,3,4,2 Sqn No 1 Elementary Flying Training School,\N,None,WYT,None,United Kingdom,N
4,4,5,213 Flight Unit,\N,None,TFU,None,Russia,N

# ☑️ Sorting results

**Q7)** Refer to `name`, `country`, and `altitude` columns in the `airports` table. Find the 5 airports with the highest `altitude`.

See below code syntax for some guidance:
```SQL
SELECT name, country, altitude
FROM airports
ORDER BY <column_name> [ASC/DESC]
LIMIT 5;
```
Please note you have been provided with the code for this question to carry out the necessary analysis work. Simply run the code cell to produce the desired results.

In [12]:
query = """
SELECT name, country, altitude
FROM airports
ORDER BY altitude DESC
LIMIT 5;
"""

df = pd.read_sql_query(query, conn)
df

             name  country altitude
0  Dauphin Barker   Canada      999
1           Akola    India      999
2       Flin Flon   Canada      997
3        Bellevue   France      997
4        Tiputini  Ecuador      997

Please note that the `altitude` column in the `airports` table has been assigned the TEXT data type, which would cause data within this column to be improperly sorted

The report you see above is misleading. To address this issue, In the following section, we will utilize the SQL `CAST()` function to correct the error displayed in the report above.